### PR TITLE
Homepage

### PR DESCRIPTION
**Pull request by melissachow0**
Finished movie home page, I can add queries for genres later  but overall the page is finished.

### CODE REVIEW

**Comment by Fenlongo** [comment]
Homepage looks good. All the tests are passing so that's a good sign. Solid work

**Comment by HoldenEv** [comment]
looks good well done passing the CI/CD checks

**Review by lukaschou — CHANGES_REQUESTED** [review]
Hey the frontend changes look good but please unstage/uncommit the node_modules folder. I don't know how that was added but it should not be pushed to the repository.

**Comment by nickli1209** [comment]
looks good, I'll try write some more homepage queries for you

**Pull request merged**
