### PR TITLE
User page

### PR DESCRIPTION
**Pull request by Fenlongo**

### CODE REVIEW

**Comment by nickli1209** [comment]
looks good! Might be worth rerunning the deployment build before merging, just to make sure it builds fine given it was stopped by a conflict...

**Comment by HoldenEv** [comment]
looks great but it looks like the backend deployment failed.

**Review by lukaschou — APPROVED** [review]
Looks good to me

**Comment by melissachow0** [comment]
Looks great Tobe! Cool new features

**Pull request merged**
