### PR TITLE
Local db testing and azure blob

### PR DESCRIPTION
**Pull request by nickli1209**
have 100% model coverage, around 50% controller coverage, will keep working on controller in the future. I also added/integrated azure blob storage for profile pictures since the s3 bucket couldn't be merged, the route to hit the uploadProfilePicture routes is ".../authentication/uploadProfilePicture", this returns the hosted image address. Need to send a file with the key file in the req.body.

### CODE REVIEW

**Comment by Fenlongo** [comment]
Looks pretty good. However the front end tests are failing. might want to run the commands again and fix any errors

**Comment by nickli1209** [comment]
> Looks pretty good. However the front end tests are failing. might want to run the commands again and fix any errors

Just did all good now, good catch G

**Review by lukaschou — APPROVED** [review]
Don't really have time to review all the tests but the frontend stuff looks good to me.

**Comment by melissachow0** [comment]
Looks good Nick, good job getting image storage working.

**Comment by HoldenEv** [comment]
Tests look solid going to local storage for testing was e great decision.

**Pull request merged**
